PIPELINE: str = "pipeline"
PIPES: str = "pipes"
NAME: str = "name"
OUTPUT: str = "output"
SRC_CLS: str = "src_cls"
EXECUTION_STEPS: str = "execution_steps"
ARGS: str = "args"
CORPUS_DIR: str = "corpus_dir"
